[theme]
base = "light"
primaryColor = "#4CAF50"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[browser]
title = "XLS and CSV to SQL Converter"
page_icon = "media/5e0706fd002e536e.png"
